# Generated by Django 3.2.4 on 2021-08-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210819_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_isbn',
            field=models.CharField(default='no_isbn', max_length=200),
            preserve_default=False,
        ),
    ]
