# Generated by Django 3.2.4 on 2021-08-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_book_book_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_thumbnail',
            field=models.CharField(max_length=200),
        ),
    ]
